name: Release Windows

on:
  push: 
    paths: 
      - .github/workflows/release_windows.yml

jobs:
  release_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Windows Build For Release
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: Test Build Windows